language: ruby
rvm:
- 2.2.2
cache: bundler
bundler_args: "--without development"
sudo: false
before_script:
- psql -c 'create database veterator_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:migrate
addons:
  postgresql: '9.3'
  code_climate:
    repo_token: 09c1d3d72c61abdbc3d9def5322f5dc1d97a59ba77a8146be8fc2520f47e227c
deploy:
  provider: heroku
  api_key:
    secure: AuqRajfWl7n6hyPxuH8wdQUnCnMO6iEQZ8DHoocgmee8uX/6JjMkE7VTHSYt9Ao4y9DYt5ONMBp/1KMx7RY3zVZwsoSge73FtJN7Xs1BdtkFJsFzv77MWHiszoqmRZKpZCUP++R9WhlkYfbEqBod7lEHR9gVjT+PjV0w9b1pxMs=
  app: veterator
  run: "rake db:migrate"
  on:
    repo: flower-pot/veterator
