files:
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql/data/
db:
  image: postgres:9.4
  volumes_from:
    - files
  ports:
    - "5432"
web:
  build: .
  volumes:
    - .:/usr/src/app
  ports:
    - "5000:5000"
  links:
    - db:db
  env_file: .env

